import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins, Volkhov } from 'next/font/google'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({ subsets: ['latin'], weight: ["400", "500", "600", "700"] })
const volkhov = Volkhov({ subsets: ['latin'], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: "travel-Agancy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={[poppins.className, volkhov.className].toString()}>{children}</body>
    </html>
  );
}
